version: '3.8'

services:
  cockroach1:
    image: cockroachdb/cockroach:latest
    container_name: crdb-node1
    hostname: crdb-node1
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach1:/cockroach/cockroach-data
    command: start --insecure --store=node1 --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=crdb-node1:26257,crdb-node2:26257,crdb-node3:26257 --advertise-addr=crdb-node1:26257

  cockroach2:
    image: cockroachdb/cockroach:latest
    container_name: crdb-node2
    hostname: crdb-node2
    ports:
      - "26258:26257"
      - "8081:8080"
    volumes:
      - cockroach2:/cockroach/cockroach-data
    command: start --insecure --store=node2 --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=crdb-node1:26257,crdb-node2:26257,crdb-node3:26257 --advertise-addr=crdb-node2:26257

  cockroach3:
    image: cockroachdb/cockroach:latest
    container_name: crdb-node3
    hostname: crdb-node3
    ports:
      - "26259:26257"
      - "8082:8080"
    volumes:
      - cockroach3:/cockroach/cockroach-data
    command: start --insecure --store=node3 --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=crdb-node1:26257,crdb-node2:26257,crdb-node3:26257 --advertise-addr=crdb-node3:26257

  init-cluster:
    image: cockroachdb/cockroach:latest
    depends_on:
      - cockroach1
      - cockroach2
      - cockroach3
    command: |
      bash -c "
        sleep 10 &&
        ./cockroach init --insecure --host=crdb-node1:26257
      "

volumes:
  cockroach1:
  cockroach2:
  cockroach3: