server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webmvc:
          routes:
            - id: sensor-data-collector
              uri: lb://SERVICIO-SENSOR
              predicates:
                - Path=/api/conjunta/2p/sensor-readings/**
              filters:
                - StripPrefix=3
            - id: environmental-analyzer
              uri: lb://SERVICIO-ENVIRONMENTAL
              predicates:
                - Path=/api/conjunta/2p/environmental/**
              filters:
                - StripPrefix=3
            - id: notification-dispatcher
              uri: lb://SERVICIO-NOTIFICATION
              predicates:
                - Path=/api/conjunta/2p/notifications/**
              filters:
                - StripPrefix=3

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always